services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7673608151:AAEOpR9o19HwBTNw_RwdMl6jyPb966QTdtQ  # or use "fromDatabase" if stored elsewhere

  - type: web
    name: twitter-auth-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn auth_server:app
    plan: free
    envVars:
      - key: TWITTER_CLIENT_ID
        value: TThacWtUVVZlY2RiMFExQm5YSTk6MTpjaQ
      - key: TWITTER_CLIENT_SECRET
        value: jIXgzwTvsxnD1Kg_T_JFrsXDTug3NLGuZ8teQ-M-cJankpg2GL
      - key: FLASK_SECRET
        value: 6532ef02544b28dd9ad89469b06fad941753a8d0c7f411ab2b0a057a161facac
      - key: REDIRECT_URI
        value: https://twitter-auth-server-qmqj.onrender.com/callback  # your render URL

