services:
  - type: web
    name: twitter-auth-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn auth_server:app"
    envVars:
      - key: PORT
        value: 8000
